# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    # デフォルト引数をわざわざ指定してもOKとする。意図した指定の場合もあるため。
    # - avoid_redundant_argument_values
    - avoid_returning_null
    # deprecated: https://dart-lang.github.io/linter/lints/avoid_returning_null_for_future.html
    #    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - combinators_ordering
    - comment_references
    - dangling_library_doc_comments
    - deprecated_consistency
    - deprecated_member_use_from_same_package
    - directives_ordering
    # - discarded_futures
    # - do_not_use_environment
    # - enable_null_safety
    - eol_at_end_of_file
    # - flutter_style_todos
    - implicit_reopen
    - invalid_case_patterns
    - join_return_with_assignment
    - library_annotations
    - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - matching_super_parameters
    - no_adjacent_strings_in_list
    - no_default_cases
    - no_leading_underscores_for_local_identifiers
    - no_literal_bool_comparisons
    - noop_primitive_operations
    # - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    # - prefer_int_literals
    - prefer_single_quotes
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - sort_constructors_first
    # ignore because group by function
    # - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_literal_in_constant_pattern
    - unawaited_futures
    # - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_library_directive
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_to_list_in_spreads
    - unreachable_from_main
    - unsafe_html
    - use_colored_box
    - use_decorated_box
    - use_enums
    # - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
