arb-dir: dev_resource/string
template-arb-file: app_ja.arb
# output-dirはビルド時に自動生成しない（synthetic-package: false）の時のみ有効
# output-dir: lib/presentation/resource
output-localization-file: l10n.dart
output-class: L10n
synthetic-package: true
preferred-supported-locales: ja
nullable-getter: false
suppress-warnings: false
untranslated-messages-file: need_translate.json